name: Limitless
version: '1.0.0'
main: com.NguyenDevs.limitless.Limitless
api-version: '1.21'
authors: [NguyenDevs]
description: A plugin that adds Gojo Satoru's Limitless ability.
softdepend:
  - PlaceholderAPI

commands:
  limitless:
    description: Main command for Limitless
    aliases: [lm]
    usage: /<command> [reload]
    permission: limitless.admin

permissions:
  limitless.use:
    description: Allows usage of all Limitless abilities
    default: op
    children:
      limitless.use.purple: true
      limitless.use.infinity: true
  limitless.use.purple:
    description: Allows usage of Purple ability
    default: op
  limitless.use.infinity:
    description: Allows usage of Infinity ability
    default: op
  limitless.admin:
    description: Allows administration of the plugin
    default: op
